### ISSUE TITLE
Possible to generate cert before DNS is set?

### ISSUE THREAD

**Issue by MickeyKay** [gregplaysguitar/acme-webfaction#2]
First of all, this is awesome! Thanks so much for creating this tool.

Secondly, is it possible to issue a cert for a domain using a host to which DNS hasn't yet been pointed? For example, say domain abc.com is currently pointed to a temp landing page on server A, but I'm building the production site on server B. When the site is done, I want to switch DNS to point to server B and have SSL set up and ready to go. When I SSH into server B and attempt to run `acme.sh --issue -w /webapps/abc/ -d abc.com -d www.abc.com`

. . . I get the following:
```
abc.com:Can not write token to file : /webapps/abc/.well-known/acme-challenge/{key-redacted-just-in-case}
```

Running the same command with `--debug` yields a bit more detail:
```
abc.com:Verify error:Invalid response from http://abc.com/.well-known/acme-challenge/{key-redacted-just-in-case} [123.45.678.91]: 404
```

Clearly the attempt to fetch the challenge endpoint isn't going to work since DNS isn't pointing to the server I'm SSH'ed into. Is there a way to bypass this check somehow? Thanks!

**Comment by gregplaysguitar** [comment]
Hi, no problem - glad it's useful!

I think you could use acme.sh [DNS mode](https://github.com/Neilpang/acme.sh#8-use-dns-mode) to create the certificate in this case, so you would add the `--dns` flag instead of `-w webroot` for the first step.
