### ISSUE TITLE
Base64 encode passwords

### ISSUE THREAD

**Issue by coreyworrell** [gregplaysguitar/acme-webfaction#3]
When using a WebFaction password with special characters that have meaning in Bash (`<$>|` etc), acme.sh does not work correctly. If you escape these characters in your password for the `Le_Reloadcmd` config option, the next time it renews it will overwrite that file with an unescaped version (`pass\>word` is re-written as `pass>word` by acme.sh).

@Neilpang recommends here https://github.com/Neilpang/acme.sh/issues/336 to base64 encode passwords instead.. I don't think this is a perfect solution, but until WebFaction completes their LE integration (if they ever do?) this could work. `acme_webfaction.py` can easily decode the password upon connecting to the API.

What do you think?

**Comment by gregplaysguitar** [comment]
Sounds sensible - I don't have time to implement this right now, but very happy to merge it if you could make a PR? Feel free to ping me here if you want any pointers
