### ISSUE TITLE
How to reset the password.

### ISSUE THREAD

**Issue by danielstrum** [gregplaysguitar/acme-webfaction#6]
Hi... I'm wondering how I would reset the password. Should I just re-run:
`acme.sh --install-cert -d example.com -d www.example.com \
--reloadcmd "WF_SERVER=WebXX WF_USER=user WF_PASSWORD=pass WF_CERT_NAME=certname acme_webfaction.py"`
with the new password?
Thanks!

**Comment by gregplaysguitar** [comment]
The script only uses the password at install time, so you shouldn't need to do anything
