### ISSUE TITLE
Step 3 - acme_webfaction.py: command not found

### ISSUE THREAD

**Issue by nuthinking** [gregplaysguitar/acme-webfaction#8]
Thank you so much for this script. All good until step 3. Running the `acme.sh --install-cert ...` command I get:

```
[Tue  3 Jul 16:03:15 UTC 2018] Run reload cmd: WF_SERVER=Web... acme_webfaction.py
/home/xxx/.acme.sh/acme.sh: line 4724: acme_webfaction.py: command not found
[Tue  3 Jul 16:03:15 UTC 2018] Reload error for :
```

Regardless if I run this from the user home or from its bin folder. `acme_webfaction.py` has the following permissions: `-rwxrwxr-x` Any idea what is going on? Thanks!

**Comment by nuthinking** [comment]
I guess my bin folder is not used properly or the python files are not executed.

**Comment by nuthinking** [comment]
Yes, my `bin` folder was missing in the executable paths. Maybe this info can be added?

**Comment by gregplaysguitar** [comment]
Fair call, I'll add a note to the readme
